package one.devos.nautical.SofterPastels.common;

import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.level.ItemLike;

import static one.devos.nautical.SofterPastels.common.SofterPastelsBlocks.*;
import static one.devos.nautical.SofterPastels.common.SofterPastelsItems.*;

public class SofterPastelsTab {
    public static void build(CreativeModeTab.ItemDisplayParameters params, CreativeModeTab.Output output) {
        addBlocks(output);
        addDecorations(output);
        addCandy(output);
        addIceCream(output);
        addPowder(output);
    }

    private static void addBlocks(CreativeModeTab.Output output) {
        addAll(output, WHITE_PASTEL_BLOCK, WHITE_PASTEL_POWDER_BLOCK, WHITE_PASTEL_SLAB_BLOCK, WHITE_PASTEL_STAIR_BLOCK, WHITE_PASTEL_WOOL_BLOCK, WHITE_PASTEL_LIGHT_BLOCK);
        addAll(output, LIGHT_RED_PASTEL_BLOCK, LIGHT_RED_PASTEL_POWDER_BLOCK, LIGHT_RED_PASTEL_SLAB_BLOCK, LIGHT_RED_PASTEL_STAIR_BLOCK, LIGHT_RED_PASTEL_WOOL_BLOCK, LIGHT_RED_PASTEL_LIGHT_BLOCK);
        addAll(output, RED_PASTEL_BLOCK, RED_PASTEL_POWDER_BLOCK, RED_PASTEL_SLAB_BLOCK, RED_PASTEL_STAIR_BLOCK, RED_PASTEL_WOOL_BLOCK, RED_PASTEL_LIGHT_BLOCK);
        addAll(output, ORANGE_PASTEL_BLOCK, ORANGE_PASTEL_POWDER_BLOCK, ORANGE_PASTEL_SLAB_BLOCK, ORANGE_PASTEL_STAIR_BLOCK, ORANGE_PASTEL_WOOL_BLOCK, ORANGE_PASTEL_LIGHT_BLOCK);
        addAll(output, YELLOW_PASTEL_BLOCK, YELLOW_PASTEL_POWDER_BLOCK, YELLOW_PASTEL_SLAB_BLOCK, YELLOW_PASTEL_STAIR_BLOCK, YELLOW_PASTEL_WOOL_BLOCK, YELLOW_PASTEL_LIGHT_BLOCK);
        addAll(output, LIGHT_GREEN_PASTEL_BLOCK, LIGHT_GREEN_PASTEL_POWDER_BLOCK, LIGHT_GREEN_PASTEL_SLAB_BLOCK, LIGHT_GREEN_PASTEL_STAIR_BLOCK, LIGHT_GREEN_PASTEL_WOOL_BLOCK, LIGHT_GREEN_PASTEL_LIGHT_BLOCK);
        addAll(output, GREEN_PASTEL_BLOCK, GREEN_PASTEL_POWDER_BLOCK, GREEN_PASTEL_SLAB_BLOCK, GREEN_PASTEL_STAIR_BLOCK, GREEN_PASTEL_WOOL_BLOCK, GREEN_PASTEL_LIGHT_BLOCK);
        addAll(output, LIGHT_BLUE_PASTEL_BLOCK, LIGHT_BLUE_PASTEL_POWDER_BLOCK, LIGHT_BLUE_PASTEL_SLAB_BLOCK, LIGHT_BLUE_PASTEL_STAIR_BLOCK, LIGHT_BLUE_PASTEL_WOOL_BLOCK, LIGHT_BLUE_PASTEL_LIGHT_BLOCK);
        addAll(output, BLUE_PASTEL_BLOCK, BLUE_PASTEL_POWDER_BLOCK, BLUE_PASTEL_SLAB_BLOCK, BLUE_PASTEL_STAIR_BLOCK, BLUE_PASTEL_WOOL_BLOCK, BLUE_PASTEL_LIGHT_BLOCK);
        addAll(output, PURPLE_PASTEL_BLOCK, PURPLE_PASTEL_POWDER_BLOCK, PURPLE_PASTEL_SLAB_BLOCK, PURPLE_PASTEL_STAIR_BLOCK, PURPLE_PASTEL_WOOL_BLOCK, PURPLE_PASTEL_LIGHT_BLOCK);
        addAll(output, MAGENTA_PASTEL_BLOCK, MAGENTA_PASTEL_POWDER_BLOCK, MAGENTA_PASTEL_SLAB_BLOCK, MAGENTA_PASTEL_STAIR_BLOCK, MAGENTA_PASTEL_WOOL_BLOCK, MAGENTA_PASTEL_LIGHT_BLOCK);
        addAll(output, BROWN_PASTEL_BLOCK, BROWN_PASTEL_POWDER_BLOCK, BROWN_PASTEL_SLAB_BLOCK, BROWN_PASTEL_STAIR_BLOCK, BROWN_PASTEL_WOOL_BLOCK, BROWN_PASTEL_LIGHT_BLOCK);
        addAll(output, LIGHT_GRAY_PASTEL_BLOCK, LIGHT_GRAY_PASTEL_POWDER_BLOCK, LIGHT_GRAY_PASTEL_SLAB_BLOCK, LIGHT_GRAY_PASTEL_STAIR_BLOCK, LIGHT_GRAY_PASTEL_WOOL_BLOCK, LIGHT_GRAY_PASTEL_LIGHT_BLOCK);
        addAll(output, GRAY_PASTEL_BLOCK, GRAY_PASTEL_POWDER_BLOCK, GRAY_PASTEL_SLAB_BLOCK, GRAY_PASTEL_STAIR_BLOCK, GRAY_PASTEL_WOOL_BLOCK, GRAY_PASTEL_LIGHT_BLOCK);
        addAll(output, BLACK_PASTEL_BLOCK, BLACK_PASTEL_POWDER_BLOCK, BLACK_PASTEL_SLAB_BLOCK, BLACK_PASTEL_STAIR_BLOCK, BLACK_PASTEL_WOOL_BLOCK, BLACK_PASTEL_LIGHT_BLOCK);
    }

    private static void addDecorations(CreativeModeTab.Output output) {
        addAll(output, WHITE_PASTEL_FENCE_BLOCK, WHITE_PASTEL_FENCE_GATE_BLOCK, WHITE_PASTEL_WALL_BLOCK, WHITE_PASTEL_CARPET_BLOCK);
        addAll(output, LIGHT_RED_PASTEL_FENCE_BLOCK, LIGHT_RED_PASTEL_FENCE_GATE_BLOCK, LIGHT_RED_PASTEL_WALL_BLOCK, LIGHT_RED_PASTEL_CARPET_BLOCK);
        addAll(output, RED_PASTEL_FENCE_BLOCK, RED_PASTEL_FENCE_GATE_BLOCK, RED_PASTEL_WALL_BLOCK, RED_PASTEL_CARPET_BLOCK);
        addAll(output, ORANGE_PASTEL_FENCE_BLOCK, ORANGE_PASTEL_FENCE_GATE_BLOCK, ORANGE_PASTEL_WALL_BLOCK, ORANGE_PASTEL_CARPET_BLOCK);
        addAll(output, YELLOW_PASTEL_FENCE_BLOCK, YELLOW_PASTEL_FENCE_GATE_BLOCK, YELLOW_PASTEL_WALL_BLOCK, YELLOW_PASTEL_CARPET_BLOCK);
        addAll(output, LIGHT_GREEN_PASTEL_FENCE_BLOCK, LIGHT_GREEN_PASTEL_FENCE_GATE_BLOCK, LIGHT_GREEN_PASTEL_WALL_BLOCK, LIGHT_GREEN_PASTEL_CARPET_BLOCK);
        addAll(output, GREEN_PASTEL_FENCE_BLOCK, GREEN_PASTEL_FENCE_GATE_BLOCK, GREEN_PASTEL_WALL_BLOCK, GREEN_PASTEL_CARPET_BLOCK);
        addAll(output, LIGHT_BLUE_PASTEL_FENCE_BLOCK, LIGHT_BLUE_PASTEL_FENCE_GATE_BLOCK, LIGHT_BLUE_PASTEL_WALL_BLOCK, LIGHT_BLUE_PASTEL_CARPET_BLOCK);
        addAll(output, BLUE_PASTEL_FENCE_BLOCK, BLUE_PASTEL_FENCE_GATE_BLOCK, BLUE_PASTEL_WALL_BLOCK, BLUE_PASTEL_CARPET_BLOCK);
        addAll(output, PURPLE_PASTEL_FENCE_BLOCK, PURPLE_PASTEL_FENCE_GATE_BLOCK, PURPLE_PASTEL_WALL_BLOCK, PURPLE_PASTEL_CARPET_BLOCK);
        addAll(output, MAGENTA_PASTEL_FENCE_BLOCK, MAGENTA_PASTEL_FENCE_GATE_BLOCK, MAGENTA_PASTEL_WALL_BLOCK, MAGENTA_PASTEL_CARPET_BLOCK);
        addAll(output, BROWN_PASTEL_FENCE_BLOCK, BROWN_PASTEL_FENCE_GATE_BLOCK, BROWN_PASTEL_WALL_BLOCK, BROWN_PASTEL_CARPET_BLOCK);
        addAll(output, LIGHT_GRAY_PASTEL_FENCE_BLOCK, LIGHT_GRAY_PASTEL_FENCE_GATE_BLOCK, LIGHT_GRAY_PASTEL_WALL_BLOCK, LIGHT_GRAY_PASTEL_CARPET_BLOCK);
        addAll(output, GRAY_PASTEL_FENCE_BLOCK, GRAY_PASTEL_FENCE_GATE_BLOCK, GRAY_PASTEL_WALL_BLOCK, GRAY_PASTEL_CARPET_BLOCK);
        addAll(output, BLACK_PASTEL_FENCE_BLOCK, BLACK_PASTEL_FENCE_GATE_BLOCK, BLACK_PASTEL_WALL_BLOCK, BLACK_PASTEL_CARPET_BLOCK);
    }

    private static void addCandy(CreativeModeTab.Output output) {
        addAll(output, WHITE_TAFFY, WHITE_COTTON_CANDY, WHITE_HARD_CANDY);
        addAll(output, LIGHT_RED_TAFFY, LIGHT_RED_COTTON_CANDY, LIGHT_RED_HARD_CANDY);
        addAll(output, RED_TAFFY, RED_COTTON_CANDY, RED_HARD_CANDY);
        addAll(output, ORANGE_TAFFY, ORANGE_COTTON_CANDY, ORANGE_HARD_CANDY);
        addAll(output, YELLOW_TAFFY, YELLOW_COTTON_CANDY, YELLOW_HARD_CANDY);
        addAll(output, LIGHT_GREEN_TAFFY, LIGHT_GREEN_COTTON_CANDY, LIGHT_GREEN_HARD_CANDY);
        addAll(output, GREEN_TAFFY, GREEN_COTTON_CANDY, GREEN_HARD_CANDY);
        addAll(output, LIGHT_BLUE_TAFFY, LIGHT_BLUE_COTTON_CANDY, LIGHT_BLUE_HARD_CANDY);
        addAll(output, BLUE_TAFFY, BLUE_COTTON_CANDY, BLUE_HARD_CANDY);
        addAll(output, PURPLE_TAFFY, PURPLE_COTTON_CANDY, PURPLE_HARD_CANDY);
        addAll(output, MAGENTA_TAFFY, MAGENTA_COTTON_CANDY, MAGENTA_HARD_CANDY);
        addAll(output, BROWN_TAFFY, BROWN_COTTON_CANDY, BROWN_HARD_CANDY);
        addAll(output, LIGHT_GRAY_TAFFY, LIGHT_GRAY_COTTON_CANDY, LIGHT_GRAY_HARD_CANDY);
        addAll(output, GRAY_TAFFY, GRAY_COTTON_CANDY, GRAY_HARD_CANDY);
        addAll(output, BLACK_TAFFY, BLACK_COTTON_CANDY, BLACK_HARD_CANDY);
    }

    private static void addIceCream(CreativeModeTab.Output output) {
        addAll(output, COTTON_CANDY_ICE_CREAM, CHOCOLATE_ICE_CREAM, STRAWBERRY_ICE_CREAM, VANILLA_ICE_CREAM);
    }

    private static void addPowder(CreativeModeTab.Output output) {
        output.accept(WHITE_POWDER);
        output.accept(LIGHT_RED_POWDER);
        output.accept(RED_POWDER);
        output.accept(ORANGE_POWDER);
        output.accept(YELLOW_POWDER);
        output.accept(LIGHT_GREEN_POWDER);
        output.accept(GREEN_POWDER);
        output.accept(LIGHT_BLUE_POWDER);
        output.accept(BLUE_POWDER);
        output.accept(PURPLE_POWDER);
        output.accept(BROWN_POWDER);
        output.accept(LIGHT_GRAY_POWDER);
        output.accept(GRAY_POWDER);
        output.accept(BLACK_POWDER);

        output.accept(POWDER);
    }

    private static void addAll(CreativeModeTab.Output output, ItemLike... items) {
        for (ItemLike item : items) {
            output.accept(item);
        }
    }
}
