package one.devos.nautical.SofterPastels.common;

import io.wispforest.owo.itemgroup.OwoItemSettings;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import one.devos.nautical.SofterPastels.utils.CandyTooltipItem;

import static one.devos.nautical.SofterPastels.SofterPastels.SP_ITEM_GROUP;
import static one.devos.nautical.SofterPastels.utils.Register.registerItem;

public class SofterPastelsItems {
    public static int SecondsToTicks(int seconds) {
        return seconds * 20;
    }

    public static final CandyTooltipItem WHITE_TAFFY = (CandyTooltipItem) registerItem("white_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.INVISIBILITY, SecondsToTicks(30), 0), 1.0F).build()), "item.softerpastels.white_taffy.description_2"));
    public static final CandyTooltipItem WHITE_COTTON_CANDY = (CandyTooltipItem) registerItem("white_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.INVISIBILITY, SecondsToTicks(15), 0), 1.0F).build()), "item.softerpastels.white_cotton_candy.description_2"));
    public static final CandyTooltipItem WHITE_HARD_CANDY = (CandyTooltipItem) registerItem("white_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.INVISIBILITY, SecondsToTicks(240), 0), 1.0F).build()), "items.softerpastels.white_hard_candy.description_2"));

    public static final CandyTooltipItem LIGHT_RED_TAFFY = (CandyTooltipItem) registerItem("light_red_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.REGENERATION, SecondsToTicks(15), 0), 1.0F).build()), "item.softerpastels.light_red_taffy.description_2"));
    public static final CandyTooltipItem LIGHT_RED_COTTON_CANDY = (CandyTooltipItem) registerItem("light_red_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.REGENERATION, SecondsToTicks(7), 1), 1.0F).build()), "item.softerpastels.light_red_cotton_candy.description_2"));
    public static final CandyTooltipItem LIGHT_RED_HARD_CANDY = (CandyTooltipItem) registerItem("light_red_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.REGENERATION, SecondsToTicks(120), 2), 1.0F).build()), "items.softerpastels.light_red_hard_candy.description_2"));

    public static final CandyTooltipItem RED_TAFFY = (CandyTooltipItem) registerItem("red_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.HEALTH_BOOST, 1, 0), 1.0F).build()), "item.softerpastels.red_taffy.description_2"));
    public static final CandyTooltipItem RED_COTTON_CANDY = (CandyTooltipItem) registerItem("red_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.HEALTH_BOOST, 1, 1), 1.0F).build()), "item.softerpastels.red_cotton_candy.description_2"));
    public static final CandyTooltipItem RED_HARD_CANDY = (CandyTooltipItem) registerItem("red_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.HEALTH_BOOST, 1, 2), 1.0F).build()), "item.softerpastels.red_hard_candy.description_2"));

    public static final CandyTooltipItem ORANGE_TAFFY = (CandyTooltipItem) registerItem("orange_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.FIRE_RESISTANCE, SecondsToTicks(15), 0), 1.0F).build()), "item.softerpastels.orange_taffy.description_2"));
    public static final CandyTooltipItem ORANGE_COTTON_CANDY = (CandyTooltipItem) registerItem("orange_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.FIRE_RESISTANCE, SecondsToTicks(7), 1), 1.0F).build()), "item.softerpastels.orange_cotton_candy.description_2"));
    public static final CandyTooltipItem ORANGE_HARD_CANDY = (CandyTooltipItem) registerItem("orange_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.FIRE_RESISTANCE, SecondsToTicks(120), 2), 1.0F).build()), "item.softerpastels.orange_hard_candy.description_2"));

    public static final CandyTooltipItem YELLOW_TAFFY = (CandyTooltipItem) registerItem("yellow_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.DIG_SPEED, SecondsToTicks(45), 0), 1.0F).build()), "item.softerpastels.yellow_taffy.description_2"));
    public static final CandyTooltipItem YELLOW_COTTON_CANDY = (CandyTooltipItem) registerItem("yellow_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.DIG_SPEED, SecondsToTicks(22), 1), 1.0F).build()), "item.softerpastels.yellow_cotton_candy.description_2"));
    public static final CandyTooltipItem YELLOW_HARD_CANDY = (CandyTooltipItem) registerItem("yellow_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.DIG_SPEED, SecondsToTicks(360), 2), 1.0F).build()), "item.softerpastels.yellow_hard_candy.description_2"));

    public static final CandyTooltipItem LIGHT_GREEN_TAFFY = (CandyTooltipItem) registerItem("light_green_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.JUMP, SecondsToTicks(60), 0), 1.0F).build()), "item.softerpastels.light_green_taffy.description_2"));
    public static final CandyTooltipItem LIGHT_GREEN_COTTON_CANDY = (CandyTooltipItem) registerItem("light_green_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.JUMP, SecondsToTicks(30), 1), 1.0F).build()), "item.softerpastels.light_green_cotton_candy.description_2"));
    public static final CandyTooltipItem LIGHT_GREEN_HARD_CANDY = (CandyTooltipItem) registerItem("light_green_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.JUMP, SecondsToTicks(480), 2), 1.0F).build()), "item.softerpastels.light_green_hard_candy.description_2"));

    public static final CandyTooltipItem GREEN_TAFFY = (CandyTooltipItem) registerItem("green_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.LUCK, SecondsToTicks(180), 0), 1.0F).build()), "item.softerpastels.green_taffy.description_2"));
    public static final CandyTooltipItem GREEN_COTTON_CANDY = (CandyTooltipItem) registerItem("green_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.LUCK, SecondsToTicks(90), 1), 1.0F).build()), "item.softerpastels.green_cotton_candy.description_2"));
    public static final CandyTooltipItem GREEN_HARD_CANDY = (CandyTooltipItem) registerItem("green_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.LUCK, SecondsToTicks(1440), 2), 1.0F).build()), "item.softerpastels.green_hard_candy.description_2"));

    public static final CandyTooltipItem LIGHT_BLUE_TAFFY = (CandyTooltipItem) registerItem("light_blue_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, SecondsToTicks(60), 0), 1.0F).build()), "item.softerpastels.light_blue_taffy.description_2"));
    public static final CandyTooltipItem LIGHT_BLUE_COTTON_CANDY = (CandyTooltipItem) registerItem("light_blue_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, SecondsToTicks(30), 1), 1.0F).build()), "item.softerpastels.light_blue_cotton_candy.description_2"));
    public static final CandyTooltipItem LIGHT_BLUE_HARD_CANDY = (CandyTooltipItem) registerItem("light_blue_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, SecondsToTicks(480), 2), 1.0F).build()), "item.softerpastels.light_blue_hard_candy.description_2"));

    public static final CandyTooltipItem BLUE_TAFFY = (CandyTooltipItem) registerItem("blue_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.WATER_BREATHING, SecondsToTicks(15), 0), 1.0F).build()), "item.softerpastels.blue_taffy.description_2"));
    public static final CandyTooltipItem BLUE_COTTON_CANDY = (CandyTooltipItem) registerItem("blue_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.WATER_BREATHING, SecondsToTicks(7), 1), 1.0F).build()), "item.softerpastels.blue_cotton_candy.description_2"));
    public static final CandyTooltipItem BLUE_HARD_CANDY = (CandyTooltipItem) registerItem("blue_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.WATER_BREATHING, SecondsToTicks(120), 2), 1.0F).build()), "item.softerpastels.blue_hard_candy.description_2"));

    public static final CandyTooltipItem PURPLE_TAFFY = (CandyTooltipItem) registerItem("purple_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.SLOW_FALLING, SecondsToTicks(30), 0), 1.0F).build()), "item.softerpastels.purple_taffy.description_2"));
    public static final CandyTooltipItem PURPLE_COTTON_CANDY = (CandyTooltipItem) registerItem("purple_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.SLOW_FALLING, SecondsToTicks(15), 0), 1.0F).build()), "item.softerpastels.purple_cotton_candy.description_2"));
    public static final CandyTooltipItem PURPLE_HARD_CANDY = (CandyTooltipItem) registerItem("purple_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.SLOW_FALLING, SecondsToTicks(240), 0), 1.0F).build()), "item.softerpastels.purple_hard_candy.description_2"));

    public static final CandyTooltipItem MAGENTA_TAFFY = (CandyTooltipItem) registerItem("magenta_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.GLOWING, SecondsToTicks(60), 0), 1.0F).build()), "item.softerpastels.magenta_taffy.description_2"));
    public static final CandyTooltipItem MAGENTA_COTTON_CANDY = (CandyTooltipItem) registerItem("magenta_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.GLOWING, SecondsToTicks(30), 0), 1.0F).build()), "item.softerpastels.magenta_cotton_candy.description_2"));
    public static final CandyTooltipItem MAGENTA_HARD_CANDY = (CandyTooltipItem) registerItem("magenta_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.GLOWING, SecondsToTicks(480), 0), 1.0F).build()), "item.softerpastels.magenta_hard_candy.description_2"));

    public static final CandyTooltipItem BROWN_TAFFY = (CandyTooltipItem) registerItem("brown_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.LEVITATION, SecondsToTicks(5), 0), 1.0F).build()), "item.softerpastels.brown_taffy.description_2"));
    public static final CandyTooltipItem BROWN_COTTON_CANDY = (CandyTooltipItem) registerItem("brown_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.LEVITATION, SecondsToTicks(3), 1), 1.0F).build()), "item.softerpastels.brown_cotton_candy.description_2"));
    public static final CandyTooltipItem BROWN_HARD_CANDY = (CandyTooltipItem) registerItem("brown_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.LEVITATION, SecondsToTicks(40), 2), 1.0F).build()), "item.softerpastels.brown_hard_candy.description_2"));

    public static final CandyTooltipItem LIGHT_GRAY_TAFFY = (CandyTooltipItem) registerItem("light_gray_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, SecondsToTicks(30), 0), 1.0F).build()), "item.softerpastels.light_gray_taffy.description_2"));
    public static final CandyTooltipItem LIGHT_GRAY_COTTON_CANDY = (CandyTooltipItem) registerItem("light_gray_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, SecondsToTicks(15), 1), 1.0F).build()), "item.softerpastels.light_gray_cotton_candy.description_2"));
    public static final CandyTooltipItem LIGHT_GRAY_HARD_CANDY = (CandyTooltipItem) registerItem("light_gray_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, SecondsToTicks(240), 2), 1.0F).build()), "item.softerpastels.light_gray_hard_candy.description_2"));

    public static final CandyTooltipItem GRAY_TAFFY = (CandyTooltipItem) registerItem("gray_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.ABSORPTION, SecondsToTicks(60), 0), 1.0F).build()), "item.softerpastels.gray_taffy.description_2"));
    public static final CandyTooltipItem GRAY_COTTON_CANDY = (CandyTooltipItem) registerItem("gray_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().effect(new MobEffectInstance(MobEffects.ABSORPTION, SecondsToTicks(30), 1), 1.0F).build()), "item.softerpastels.gray_cotton_candy.description_2"));
    public static final CandyTooltipItem GRAY_HARD_CANDY = (CandyTooltipItem) registerItem("gray_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().effect(new MobEffectInstance(MobEffects.ABSORPTION, SecondsToTicks(480), 2), 1.0F).build()), "item.softerpastels.gray_hard_candy.description_2"));

    public static final CandyTooltipItem BLACK_TAFFY = (CandyTooltipItem) registerItem("black_taffy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(2).saturationMod(2).fast().alwaysEat().build()), "item.softerpastels.black_taffy.description_2"));
    public static final CandyTooltipItem BLACK_COTTON_CANDY = (CandyTooltipItem) registerItem("black_cotton_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).fast().alwaysEat().build()), "item.softerpastels.black_cotton_candy.description_2"));
    public static final CandyTooltipItem BLACK_HARD_CANDY = (CandyTooltipItem) registerItem("black_hard_candy", new CandyTooltipItem(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(2).alwaysEat().build()), "item.softerpastels.black_hard_candy.description_2"));

    public static final Item COTTON_CANDY_ICE_CREAM = registerItem("cotton_candy_ice_cream", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(5).build())));
    public static final Item CHOCOLATE_ICE_CREAM = registerItem("chocolate_ice_cream", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(5).build())));
    public static final Item STRAWBERRY_ICE_CREAM = registerItem("strawberry_ice_cream", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(5).build())));
    public static final Item VANILLA_ICE_CREAM = registerItem("vanilla_ice_cream", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2).food(new FoodProperties.Builder().nutrition(3).saturationMod(5).build())));

    public static final Item WHITE_POWDER = registerItem("white_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item LIGHT_RED_POWDER = registerItem("light_red_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item RED_POWDER = registerItem("red_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item ORANGE_POWDER = registerItem("orange_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item YELLOW_POWDER = registerItem("yellow_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item LIGHT_GREEN_POWDER = registerItem("light_green_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item GREEN_POWDER = registerItem("green_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item LIGHT_BLUE_POWDER = registerItem("light_blue_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item BLUE_POWDER = registerItem("blue_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item PURPLE_POWDER = registerItem("purple_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item MAGENTA_POWDER = registerItem("magenta_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item BROWN_POWDER = registerItem("brown_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item BLACK_POWDER = registerItem("black_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item LIGHT_GRAY_POWDER = registerItem("light_gray_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));
    public static final Item GRAY_POWDER = registerItem("gray_powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));

    public static final Item POWDER = registerItem("powder", new Item(new OwoItemSettings().group(SP_ITEM_GROUP).tab(2)));

    public static void init() { }
}
