package one.devos.nautical.softerpastels.datagen

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider
import net.minecraft.core.HolderLookup
import net.minecraft.data.recipes.RecipeOutput
import net.minecraft.resources.ResourceLocation
import net.minecraft.tags.ItemTags
import one.devos.nautical.softerpastels.common.SofterPastelsBlocks
import java.util.concurrent.CompletableFuture

class SofterPastelsItemTagsProvider(output: FabricDataOutput, registriesFuture: CompletableFuture<HolderLookup.Provider>) : FabricTagProvider.ItemTagProvider(output, registriesFuture) {
    override fun addTags(arg: HolderLookup.Provider) {
        getOrCreateTagBuilder(ItemTags.FENCES)
            .add(SofterPastelsBlocks.WHITE_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_RED_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.RED_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.ORANGE_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.YELLOW_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.GREEN_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLUE_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.PURPLE_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.MAGENTA_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.BROWN_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.GRAY_PASTEL_FENCE_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLACK_PASTEL_FENCE_BLOCK.asItem())


        getOrCreateTagBuilder(ItemTags.FENCE_GATES)
            .add(SofterPastelsBlocks.WHITE_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_RED_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.RED_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.ORANGE_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.YELLOW_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.GREEN_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLUE_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.PURPLE_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.MAGENTA_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.BROWN_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.GRAY_PASTEL_FENCE_GATE_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLACK_PASTEL_FENCE_GATE_BLOCK.asItem())

        getOrCreateTagBuilder(ItemTags.WALLS)
            .add(SofterPastelsBlocks.WHITE_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_RED_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.RED_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.ORANGE_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.YELLOW_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.GREEN_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLUE_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.PURPLE_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.MAGENTA_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.BROWN_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.GRAY_PASTEL_WALL_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLACK_PASTEL_WALL_BLOCK.asItem())

        getOrCreateTagBuilder(ItemTags.WOOL_CARPETS)
            .add(SofterPastelsBlocks.WHITE_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_RED_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.RED_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.ORANGE_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.YELLOW_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.GREEN_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLUE_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.PURPLE_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.MAGENTA_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.BROWN_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.GRAY_PASTEL_CARPET_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLACK_PASTEL_CARPET_BLOCK.asItem())

        getOrCreateTagBuilder(ItemTags.WOOL)
            .add(SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_RED_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.RED_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.ORANGE_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.YELLOW_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.GREEN_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLUE_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.PURPLE_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.MAGENTA_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.BROWN_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.GRAY_PASTEL_WOOL_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLACK_PASTEL_WOOL_BLOCK.asItem())

        getOrCreateTagBuilder(ItemTags.SLABS)
            .add(SofterPastelsBlocks.WHITE_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_RED_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.RED_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.ORANGE_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.YELLOW_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.GREEN_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLUE_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.PURPLE_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.MAGENTA_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.BROWN_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.GRAY_PASTEL_SLAB_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLACK_PASTEL_SLAB_BLOCK.asItem())

        getOrCreateTagBuilder(ItemTags.STAIRS)
            .add(SofterPastelsBlocks.WHITE_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_RED_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.RED_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.ORANGE_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.YELLOW_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.GREEN_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLUE_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.PURPLE_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.MAGENTA_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.BROWN_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.GRAY_PASTEL_STAIR_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLACK_PASTEL_STAIR_BLOCK.asItem())

        getOrCreateTagBuilder(ItemTags.SMELTS_TO_GLASS)
            .add(SofterPastelsBlocks.WHITE_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_RED_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.RED_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.ORANGE_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.YELLOW_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.GREEN_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLUE_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.PURPLE_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.MAGENTA_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.BROWN_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.GRAY_PASTEL_POWDER_BLOCK.asItem())
            .add(SofterPastelsBlocks.BLACK_PASTEL_POWDER_BLOCK.asItem())
    }
}