package one.devos.nautical.softerpastels.datagen

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider
import one.devos.nautical.softerpastels.common.SofterPastelsBlocks
import one.devos.nautical.softerpastels.common.blocks.GlassBlocks

class SofterPastelsLootTableProvider(dataOutput: FabricDataOutput) : FabricBlockLootTableProvider(dataOutput) {
    override fun generate() {
        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_BLOCK)

        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_POWDER_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_POWDER_BLOCK)

        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_FENCE_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_FENCE_BLOCK)

        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_FENCE_GATE_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_FENCE_GATE_BLOCK)

        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_WALL_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_WALL_BLOCK)

        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_SLAB_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_SLAB_BLOCK)

        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_STAIR_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_STAIR_BLOCK)

        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_CARPET_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_CARPET_BLOCK)

        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_LIGHT_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_LIGHT_BLOCK)

        dropSelf(SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_RED_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.RED_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.ORANGE_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.YELLOW_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.GREEN_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.BLUE_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.PURPLE_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.MAGENTA_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.BROWN_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.GRAY_PASTEL_WOOL_BLOCK)
        dropSelf(SofterPastelsBlocks.BLACK_PASTEL_WOOL_BLOCK)

        dropWhenSilkTouch(GlassBlocks.WHITE_GLASS)
        dropWhenSilkTouch(GlassBlocks.LIGHT_RED_GLASS)
        dropWhenSilkTouch(GlassBlocks.RED_GLASS)
        dropWhenSilkTouch(GlassBlocks.ORANGE_GLASS)
        dropWhenSilkTouch(GlassBlocks.YELLOW_GLASS)
        dropWhenSilkTouch(GlassBlocks.LIGHT_GREEN_GLASS)
        dropWhenSilkTouch(GlassBlocks.GREEN_GLASS)
        dropWhenSilkTouch(GlassBlocks.LIGHT_BLUE_GLASS)
        dropWhenSilkTouch(GlassBlocks.BLUE_GLASS)
        dropWhenSilkTouch(GlassBlocks.PURPLE_GLASS)
        dropWhenSilkTouch(GlassBlocks.MAGENTA_GLASS)
        dropWhenSilkTouch(GlassBlocks.BROWN_GLASS)
        dropWhenSilkTouch(GlassBlocks.LIGHT_GRAY_GLASS)
        dropWhenSilkTouch(GlassBlocks.GRAY_GLASS)
        dropWhenSilkTouch(GlassBlocks.BLACK_GLASS)

        dropWhenSilkTouch(GlassBlocks.WHITE_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.LIGHT_RED_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.RED_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.ORANGE_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.YELLOW_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.LIGHT_GREEN_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.GREEN_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.LIGHT_BLUE_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.BLUE_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.PURPLE_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.MAGENTA_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.BROWN_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.LIGHT_GRAY_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.GRAY_GLASS_PANE)
        dropWhenSilkTouch(GlassBlocks.BLACK_GLASS_PANE)
    }
}