package one.devos.nautical.softerpastels.datagen

// dont- dont ask. please. lmao
// i might just prefix all of the calls with DataGenRecipeGenerators and then be able to star the datagen package
// this is my one major gripe with kotlin tbh, u can just DataGenRecipeGenerators.* it, cant do import-on-demand
// for object functions[?], but u can for multiple classes in a package
import gay.asoji.innerpastels.crab.CrabInTheCode
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelCarpetBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelCottonCandyItem
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelFenceBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelFenceGateBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelGlassBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelGlassPaneBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelGlassPaneRectangleBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelLightBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelPowderBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelSlabBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelStairBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelWallBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelWoolBlock
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerCraftingPastelWoolBlockV
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerPastelTaffyItem
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerSmeltingPastelGlass
import gay.asoji.innerpastels.datagen.RecipeGenerators.registerSmeltingPastelHardCandy
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider
import net.minecraft.data.recipes.RecipeOutput
import net.minecraft.world.item.Items
import net.minecraft.world.level.ItemLike
import one.devos.nautical.softerpastels.common.SofterPastelsBlocks
import one.devos.nautical.softerpastels.common.SofterPastelsItems
import one.devos.nautical.softerpastels.common.blocks.GlassBlocks
import one.devos.nautical.softerpastels.utils.helpers.datagen.DataGenRecipeGenerators.registerCraftingPastelColoredPowderItem
import one.devos.nautical.softerpastels.utils.helpers.datagen.DataGenRecipeGenerators.registerCraftingPastelPowderBaseItem

class SofterPastelsRecipeProvider(output: FabricDataOutput) : FabricRecipeProvider(output) {
    // i was forced against my own will to make a List<ItemLike> for a smelting recipe that only neeeds... 🥁🥁🥁
    // 1. fucking. item. [as of right now]
    // but then again once the sand gets added i guess this comes in handy because now 2 different blocks can make
    // the same glass! ...ughhhhhhh
    // -asoji
    private val WHITE_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.WHITE_PASTEL_POWDER_BLOCK)
    private val LIGHT_RED_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.LIGHT_RED_PASTEL_POWDER_BLOCK)
    private val RED_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.RED_PASTEL_POWDER_BLOCK)
    private val ORANGE_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.ORANGE_PASTEL_POWDER_BLOCK)
    private val YELLOW_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.YELLOW_PASTEL_POWDER_BLOCK)
    private val LIGHT_GREEN_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.LIGHT_GREEN_PASTEL_POWDER_BLOCK)
    private val GREEN_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.GREEN_PASTEL_POWDER_BLOCK)
    private val LIGHT_BLUE_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.LIGHT_BLUE_PASTEL_POWDER_BLOCK)
    private val BLUE_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.BLUE_PASTEL_POWDER_BLOCK)
    private val PURPLE_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.PURPLE_PASTEL_POWDER_BLOCK)
    private val MAGENTA_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.MAGENTA_PASTEL_POWDER_BLOCK)
    private val BROWN_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.BROWN_PASTEL_POWDER_BLOCK)
    private val LIGHT_GRAY_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.LIGHT_GRAY_PASTEL_POWDER_BLOCK)
    private val GRAY_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.GRAY_PASTEL_POWDER_BLOCK)
    private val BLACK_PASTEL_GLASS_SMELTABLES: List<ItemLike> = listOf(SofterPastelsBlocks.BLACK_PASTEL_POWDER_BLOCK)

    private val WHITE_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.WHITE_TAFFY)
    private val LIGHT_RED_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.LIGHT_RED_TAFFY)
    private val RED_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.RED_TAFFY)
    private val ORANGE_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.ORANGE_TAFFY)
    private val YELLOW_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.YELLOW_TAFFY)
    private val LIGHT_GREEN_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.LIGHT_GREEN_TAFFY)
    private val GREEN_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.GREEN_TAFFY)
    private val LIGHT_BLUE_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.LIGHT_BLUE_TAFFY)
    private val BLUE_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.BLUE_TAFFY)
    private val PURPLE_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.PURPLE_TAFFY)
    private val MAGENTA_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.MAGENTA_TAFFY)
    private val BROWN_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.BROWN_TAFFY)
    private val LIGHT_GRAY_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.LIGHT_GRAY_TAFFY)
    private val GRAY_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.GRAY_TAFFY)
    private val BLACK_PASTEL_HARD_CANDY_SMELTABLES: List<ItemLike> = listOf(SofterPastelsItems.BLACK_TAFFY)

    override fun buildRecipes(exporter: RecipeOutput) {
        registerSmeltingPastelGlass(exporter, WHITE_PASTEL_GLASS_SMELTABLES, GlassBlocks.WHITE_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, LIGHT_RED_PASTEL_GLASS_SMELTABLES, GlassBlocks.LIGHT_RED_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, RED_PASTEL_GLASS_SMELTABLES, GlassBlocks.RED_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, ORANGE_PASTEL_GLASS_SMELTABLES, GlassBlocks.ORANGE_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, YELLOW_PASTEL_GLASS_SMELTABLES, GlassBlocks.YELLOW_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, LIGHT_GREEN_PASTEL_GLASS_SMELTABLES, GlassBlocks.LIGHT_GREEN_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, GREEN_PASTEL_GLASS_SMELTABLES, GlassBlocks.GREEN_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, LIGHT_BLUE_PASTEL_GLASS_SMELTABLES, GlassBlocks.LIGHT_BLUE_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, BLUE_PASTEL_GLASS_SMELTABLES, GlassBlocks.BLUE_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, PURPLE_PASTEL_GLASS_SMELTABLES, GlassBlocks.PURPLE_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, MAGENTA_PASTEL_GLASS_SMELTABLES, GlassBlocks.MAGENTA_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, BROWN_PASTEL_GLASS_SMELTABLES, GlassBlocks.BROWN_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, LIGHT_GRAY_PASTEL_GLASS_SMELTABLES, GlassBlocks.LIGHT_GRAY_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, GRAY_PASTEL_GLASS_SMELTABLES, GlassBlocks.GRAY_GLASS_ITEM, "pastel_glass")
        registerSmeltingPastelGlass(exporter, BLACK_PASTEL_GLASS_SMELTABLES, GlassBlocks.BLACK_GLASS_ITEM, "pastel_glass")

        registerSmeltingPastelHardCandy(exporter, WHITE_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.WHITE_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, LIGHT_RED_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.LIGHT_RED_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, RED_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.RED_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, ORANGE_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.ORANGE_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, YELLOW_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.YELLOW_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, LIGHT_GREEN_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.LIGHT_GREEN_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, GREEN_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.GREEN_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, LIGHT_BLUE_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.LIGHT_BLUE_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, BLUE_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.BLUE_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, PURPLE_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.PURPLE_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, MAGENTA_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.MAGENTA_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, BROWN_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.BROWN_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, LIGHT_GRAY_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.LIGHT_GRAY_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, GRAY_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.GRAY_HARD_CANDY, "pastel_hard_candy")
        registerSmeltingPastelHardCandy(exporter, BLACK_PASTEL_HARD_CANDY_SMELTABLES, SofterPastelsItems.BLACK_HARD_CANDY, "pastel_hard_candy")

        registerCraftingPastelPowderBaseItem(exporter, Items.GLOW_BERRIES)
        registerCraftingPastelPowderBaseItem(exporter, Items.GLOW_INK_SAC)
        registerCraftingPastelPowderBaseItem(exporter, Items.GLOWSTONE_DUST)

        registerCraftingPastelColoredPowderItem(exporter, Items.WHITE_DYE, SofterPastelsItems.WHITE_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.PINK_DYE, SofterPastelsItems.LIGHT_RED_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.RED_DYE, SofterPastelsItems.RED_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.ORANGE_DYE, SofterPastelsItems.ORANGE_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.YELLOW_DYE, SofterPastelsItems.YELLOW_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.LIME_DYE, SofterPastelsItems.LIGHT_GREEN_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.GREEN_DYE, SofterPastelsItems.GREEN_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.LIGHT_BLUE_DYE, SofterPastelsItems.LIGHT_BLUE_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.BLUE_DYE, SofterPastelsItems.BLUE_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.PURPLE_DYE, SofterPastelsItems.PURPLE_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.MAGENTA_DYE, SofterPastelsItems.MAGENTA_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.BROWN_DYE, SofterPastelsItems.BROWN_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.LIGHT_GRAY_DYE, SofterPastelsItems.LIGHT_GRAY_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.GRAY_DYE, SofterPastelsItems.GRAY_POWDER)
        registerCraftingPastelColoredPowderItem(exporter, Items.BLACK_DYE, SofterPastelsItems.BLACK_POWDER)

        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.WHITE_PASTEL_BLOCK, SofterPastelsBlocks.WHITE_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.LIGHT_RED_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_RED_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.RED_PASTEL_BLOCK, SofterPastelsBlocks.RED_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.ORANGE_PASTEL_BLOCK, SofterPastelsBlocks.ORANGE_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.YELLOW_PASTEL_BLOCK, SofterPastelsBlocks.YELLOW_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.GREEN_PASTEL_BLOCK, SofterPastelsBlocks.GREEN_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.BLUE_PASTEL_BLOCK, SofterPastelsBlocks.BLUE_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.PURPLE_PASTEL_BLOCK, SofterPastelsBlocks.PURPLE_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.MAGENTA_PASTEL_BLOCK, SofterPastelsBlocks.MAGENTA_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.BROWN_PASTEL_BLOCK, SofterPastelsBlocks.BROWN_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.GRAY_PASTEL_BLOCK, SofterPastelsBlocks.GRAY_PASTEL_SLAB_BLOCK)
        registerCraftingPastelSlabBlock(exporter, SofterPastelsBlocks.BLACK_PASTEL_BLOCK, SofterPastelsBlocks.BLACK_PASTEL_SLAB_BLOCK)

        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.WHITE_PASTEL_BLOCK, SofterPastelsBlocks.WHITE_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.LIGHT_RED_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_RED_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.RED_PASTEL_BLOCK, SofterPastelsBlocks.RED_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.ORANGE_PASTEL_BLOCK, SofterPastelsBlocks.ORANGE_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.YELLOW_PASTEL_BLOCK, SofterPastelsBlocks.YELLOW_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.GREEN_PASTEL_BLOCK, SofterPastelsBlocks.GREEN_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.BLUE_PASTEL_BLOCK, SofterPastelsBlocks.BLUE_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.PURPLE_PASTEL_BLOCK, SofterPastelsBlocks.PURPLE_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.MAGENTA_PASTEL_BLOCK, SofterPastelsBlocks.MAGENTA_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.BROWN_PASTEL_BLOCK, SofterPastelsBlocks.BROWN_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.GRAY_PASTEL_BLOCK, SofterPastelsBlocks.GRAY_PASTEL_STAIR_BLOCK)
        registerCraftingPastelStairBlock(exporter, SofterPastelsBlocks.BLACK_PASTEL_BLOCK, SofterPastelsBlocks.BLACK_PASTEL_STAIR_BLOCK)

        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.WHITE_POWDER, SofterPastelsBlocks.WHITE_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.LIGHT_RED_POWDER, SofterPastelsBlocks.LIGHT_RED_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.RED_POWDER, SofterPastelsBlocks.RED_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.ORANGE_POWDER, SofterPastelsBlocks.ORANGE_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.YELLOW_POWDER, SofterPastelsBlocks.YELLOW_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.LIGHT_GREEN_POWDER, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.GREEN_POWDER, SofterPastelsBlocks.GREEN_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.LIGHT_BLUE_POWDER, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.BLUE_POWDER, SofterPastelsBlocks.BLUE_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.PURPLE_POWDER, SofterPastelsBlocks.PURPLE_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.MAGENTA_POWDER, SofterPastelsBlocks.MAGENTA_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.BROWN_POWDER, SofterPastelsBlocks.BROWN_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.LIGHT_GRAY_POWDER, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.GRAY_POWDER, SofterPastelsBlocks.GRAY_PASTEL_POWDER_BLOCK)
        registerCraftingPastelPowderBlock(exporter, SofterPastelsItems.BLACK_POWDER, SofterPastelsBlocks.BLACK_PASTEL_POWDER_BLOCK)

        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.WHITE_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.LIGHT_RED_POWDER, SofterPastelsBlocks.LIGHT_RED_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.RED_POWDER, SofterPastelsBlocks.RED_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.ORANGE_POWDER, SofterPastelsBlocks.ORANGE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.YELLOW_POWDER, SofterPastelsBlocks.YELLOW_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.LIGHT_GREEN_POWDER, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.GREEN_POWDER, SofterPastelsBlocks.GREEN_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.LIGHT_BLUE_POWDER, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.BLUE_POWDER, SofterPastelsBlocks.BLUE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.PURPLE_POWDER, SofterPastelsBlocks.PURPLE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.MAGENTA_POWDER, SofterPastelsBlocks.MAGENTA_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.BROWN_POWDER, SofterPastelsBlocks.BROWN_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.LIGHT_GRAY_POWDER, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.GRAY_POWDER, SofterPastelsBlocks.GRAY_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlockV(exporter, SofterPastelsItems.BLACK_POWDER, SofterPastelsBlocks.BLACK_PASTEL_WOOL_BLOCK)

        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.WHITE_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.LIGHT_RED_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.LIGHT_RED_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.RED_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.RED_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.ORANGE_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.ORANGE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.YELLOW_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.YELLOW_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.LIGHT_GREEN_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.GREEN_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.GREEN_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.LIGHT_BLUE_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.BLUE_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.BLUE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.PURPLE_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.PURPLE_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.MAGENTA_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.MAGENTA_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.BROWN_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.BROWN_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.LIGHT_GRAY_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.GRAY_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.GRAY_PASTEL_WOOL_BLOCK)
        registerCraftingPastelWoolBlock(exporter, SofterPastelsItems.BLACK_POWDER, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.BLACK_PASTEL_WOOL_BLOCK)

        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.WHITE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.WHITE_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.LIGHT_RED_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.LIGHT_RED_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.RED_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.RED_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.ORANGE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.ORANGE_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.YELLOW_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.YELLOW_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.GREEN_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.GREEN_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.BLUE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.BLUE_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.PURPLE_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.PURPLE_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.MAGENTA_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.MAGENTA_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.BROWN_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.BROWN_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.GRAY_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.GRAY_PASTEL_CARPET_BLOCK)
        registerCraftingPastelCarpetBlock(exporter, SofterPastelsBlocks.BLACK_PASTEL_WOOL_BLOCK, SofterPastelsBlocks.BLACK_PASTEL_CARPET_BLOCK)

        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.WHITE_PASTEL_BLOCK, SofterPastelsBlocks.WHITE_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.LIGHT_RED_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_RED_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.RED_PASTEL_BLOCK, SofterPastelsBlocks.RED_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.ORANGE_PASTEL_BLOCK, SofterPastelsBlocks.ORANGE_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.YELLOW_PASTEL_BLOCK, SofterPastelsBlocks.YELLOW_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.GREEN_PASTEL_BLOCK, SofterPastelsBlocks.GREEN_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.BLUE_PASTEL_BLOCK, SofterPastelsBlocks.BLUE_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.PURPLE_PASTEL_BLOCK, SofterPastelsBlocks.PURPLE_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.MAGENTA_PASTEL_BLOCK, SofterPastelsBlocks.MAGENTA_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.BROWN_PASTEL_BLOCK, SofterPastelsBlocks.BROWN_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.GRAY_PASTEL_BLOCK, SofterPastelsBlocks.GRAY_PASTEL_FENCE_BLOCK)
        registerCraftingPastelFenceBlock(exporter, SofterPastelsBlocks.BLACK_PASTEL_BLOCK, SofterPastelsBlocks.BLACK_PASTEL_FENCE_BLOCK)

        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.WHITE_PASTEL_BLOCK, SofterPastelsBlocks.WHITE_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.LIGHT_RED_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_RED_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.RED_PASTEL_BLOCK, SofterPastelsBlocks.RED_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.ORANGE_PASTEL_BLOCK, SofterPastelsBlocks.ORANGE_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.YELLOW_PASTEL_BLOCK, SofterPastelsBlocks.YELLOW_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.GREEN_PASTEL_BLOCK, SofterPastelsBlocks.GREEN_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.BLUE_PASTEL_BLOCK, SofterPastelsBlocks.BLUE_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.PURPLE_PASTEL_BLOCK, SofterPastelsBlocks.PURPLE_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.MAGENTA_PASTEL_BLOCK, SofterPastelsBlocks.MAGENTA_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.BROWN_PASTEL_BLOCK, SofterPastelsBlocks.BROWN_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.GRAY_PASTEL_BLOCK, SofterPastelsBlocks.GRAY_PASTEL_FENCE_GATE_BLOCK)
        registerCraftingPastelFenceGateBlock(exporter, SofterPastelsBlocks.BLACK_PASTEL_BLOCK, SofterPastelsBlocks.BLACK_PASTEL_FENCE_GATE_BLOCK)

        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.WHITE_PASTEL_BLOCK, SofterPastelsBlocks.WHITE_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.LIGHT_RED_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_RED_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.RED_PASTEL_BLOCK, SofterPastelsBlocks.RED_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.ORANGE_PASTEL_BLOCK, SofterPastelsBlocks.ORANGE_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.YELLOW_PASTEL_BLOCK, SofterPastelsBlocks.YELLOW_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.GREEN_PASTEL_BLOCK, SofterPastelsBlocks.GREEN_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.BLUE_PASTEL_BLOCK, SofterPastelsBlocks.BLUE_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.PURPLE_PASTEL_BLOCK, SofterPastelsBlocks.PURPLE_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.MAGENTA_PASTEL_BLOCK, SofterPastelsBlocks.MAGENTA_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.BROWN_PASTEL_BLOCK, SofterPastelsBlocks.BROWN_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_BLOCK, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.GRAY_PASTEL_BLOCK, SofterPastelsBlocks.GRAY_PASTEL_WALL_BLOCK)
        registerCraftingPastelWallBlock(exporter, SofterPastelsBlocks.BLACK_PASTEL_BLOCK, SofterPastelsBlocks.BLACK_PASTEL_WALL_BLOCK)

        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.WHITE_POWDER, GlassBlocks.WHITE_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.LIGHT_RED_POWDER, GlassBlocks.LIGHT_RED_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.RED_POWDER, GlassBlocks.RED_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.ORANGE_POWDER, GlassBlocks.ORANGE_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.YELLOW_POWDER, GlassBlocks.YELLOW_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.LIGHT_GREEN_POWDER, GlassBlocks.LIGHT_GREEN_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.GREEN_POWDER, GlassBlocks.GREEN_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.LIGHT_BLUE_POWDER, GlassBlocks.LIGHT_BLUE_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.BLUE_POWDER, GlassBlocks.BLUE_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.PURPLE_POWDER, GlassBlocks.PURPLE_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.MAGENTA_POWDER, GlassBlocks.MAGENTA_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.BROWN_POWDER, GlassBlocks.BROWN_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.LIGHT_GRAY_POWDER, GlassBlocks.LIGHT_GRAY_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.GRAY_POWDER, GlassBlocks.GRAY_GLASS_ITEM)
        registerCraftingPastelGlassBlock(exporter, SofterPastelsItems.BLACK_POWDER, GlassBlocks.BLACK_GLASS_ITEM)

        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.WHITE_POWDER, GlassBlocks.WHITE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.LIGHT_RED_POWDER, GlassBlocks.LIGHT_RED_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.RED_POWDER, GlassBlocks.RED_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.ORANGE_POWDER, GlassBlocks.ORANGE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.YELLOW_POWDER, GlassBlocks.YELLOW_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.LIGHT_GREEN_POWDER, GlassBlocks.LIGHT_GREEN_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.GREEN_POWDER, GlassBlocks.GREEN_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.LIGHT_BLUE_POWDER, GlassBlocks.LIGHT_BLUE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.BLUE_POWDER, GlassBlocks.BLUE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.PURPLE_POWDER, GlassBlocks.PURPLE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.MAGENTA_POWDER, GlassBlocks.MAGENTA_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.BROWN_POWDER, GlassBlocks.BROWN_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.LIGHT_GRAY_POWDER, GlassBlocks.LIGHT_GRAY_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.GRAY_POWDER, GlassBlocks.GRAY_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneBlock(exporter, SofterPastelsItems.BLACK_POWDER, GlassBlocks.BLACK_GLASS_PANE_ITEM)

        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.WHITE_GLASS_ITEM, GlassBlocks.WHITE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.LIGHT_RED_GLASS_ITEM, GlassBlocks.LIGHT_RED_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.RED_GLASS_ITEM, GlassBlocks.RED_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.ORANGE_GLASS_ITEM, GlassBlocks.ORANGE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.YELLOW_GLASS_ITEM, GlassBlocks.YELLOW_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.LIGHT_GREEN_GLASS_ITEM, GlassBlocks.LIGHT_GREEN_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.GREEN_GLASS_ITEM, GlassBlocks.GREEN_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.LIGHT_BLUE_GLASS_ITEM, GlassBlocks.LIGHT_BLUE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.BLUE_GLASS_ITEM, GlassBlocks.BLUE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.PURPLE_GLASS_ITEM, GlassBlocks.PURPLE_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.MAGENTA_GLASS_ITEM, GlassBlocks.MAGENTA_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.BROWN_GLASS_ITEM, GlassBlocks.BROWN_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.LIGHT_GRAY_GLASS_ITEM, GlassBlocks.LIGHT_GRAY_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.GRAY_GLASS_ITEM, GlassBlocks.GRAY_GLASS_PANE_ITEM)
        registerCraftingPastelGlassPaneRectangleBlock(exporter, GlassBlocks.BLACK_GLASS_ITEM, GlassBlocks.BLACK_GLASS_PANE_ITEM)

        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.WHITE_POWDER, SofterPastelsBlocks.WHITE_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.LIGHT_RED_POWDER, SofterPastelsBlocks.LIGHT_RED_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.RED_POWDER, SofterPastelsBlocks.RED_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.ORANGE_POWDER, SofterPastelsBlocks.ORANGE_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.YELLOW_POWDER, SofterPastelsBlocks.YELLOW_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.LIGHT_GREEN_POWDER, SofterPastelsBlocks.LIGHT_GREEN_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.GREEN_POWDER, SofterPastelsBlocks.GREEN_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.LIGHT_BLUE_POWDER, SofterPastelsBlocks.LIGHT_BLUE_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.BLUE_POWDER, SofterPastelsBlocks.BLUE_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.PURPLE_POWDER, SofterPastelsBlocks.PURPLE_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.MAGENTA_POWDER, SofterPastelsBlocks.MAGENTA_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.BROWN_POWDER, SofterPastelsBlocks.BROWN_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.LIGHT_GRAY_POWDER, SofterPastelsBlocks.LIGHT_GRAY_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.GRAY_POWDER, SofterPastelsBlocks.GRAY_PASTEL_LIGHT_BLOCK)
        registerCraftingPastelLightBlock(exporter, SofterPastelsItems.BLACK_POWDER, SofterPastelsBlocks.BLACK_PASTEL_LIGHT_BLOCK)

        CrabInTheCode.crabDeezNuts("im trying to make a pastel colored soup, could you add some pastel powders in?")

        registerPastelTaffyItem(exporter, SofterPastelsItems.WHITE_POWDER, SofterPastelsItems.WHITE_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.LIGHT_RED_POWDER, SofterPastelsItems.LIGHT_RED_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.RED_POWDER, SofterPastelsItems.RED_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.ORANGE_POWDER, SofterPastelsItems.ORANGE_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.YELLOW_POWDER, SofterPastelsItems.YELLOW_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.LIGHT_GREEN_POWDER, SofterPastelsItems.LIGHT_GREEN_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.GREEN_POWDER, SofterPastelsItems.GREEN_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.LIGHT_BLUE_POWDER, SofterPastelsItems.LIGHT_BLUE_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.BLUE_POWDER, SofterPastelsItems.BLUE_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.PURPLE_POWDER, SofterPastelsItems.PURPLE_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.MAGENTA_POWDER, SofterPastelsItems.MAGENTA_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.BROWN_POWDER, SofterPastelsItems.BROWN_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.LIGHT_GRAY_POWDER, SofterPastelsItems.LIGHT_GRAY_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.GRAY_POWDER, SofterPastelsItems.GRAY_TAFFY)
        registerPastelTaffyItem(exporter, SofterPastelsItems.BLACK_POWDER, SofterPastelsItems.BLACK_TAFFY)

        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.WHITE_POWDER, SofterPastelsItems.WHITE_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.LIGHT_RED_POWDER, SofterPastelsItems.LIGHT_RED_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.RED_POWDER, SofterPastelsItems.RED_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.ORANGE_POWDER, SofterPastelsItems.ORANGE_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.YELLOW_POWDER, SofterPastelsItems.YELLOW_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.LIGHT_GREEN_POWDER, SofterPastelsItems.LIGHT_GREEN_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.GREEN_POWDER, SofterPastelsItems.GREEN_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.LIGHT_BLUE_POWDER, SofterPastelsItems.LIGHT_BLUE_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.BLUE_POWDER, SofterPastelsItems.BLUE_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.PURPLE_POWDER, SofterPastelsItems.PURPLE_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.MAGENTA_POWDER, SofterPastelsItems.MAGENTA_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.BROWN_POWDER, SofterPastelsItems.BROWN_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.LIGHT_GRAY_POWDER, SofterPastelsItems.LIGHT_GRAY_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.GRAY_POWDER, SofterPastelsItems.GRAY_COTTON_CANDY)
        registerCraftingPastelCottonCandyItem(exporter, SofterPastelsItems.BLACK_POWDER, SofterPastelsItems.BLACK_COTTON_CANDY)
    }
}